# SAM configuration file for pb-fm-mcp deployment
version = 0.1

# Production Environment (main branch) - EXISTING STABLE STACK
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "pb-fm-mcp-v2"
s3_bucket = ""
s3_prefix = "pb-fm-mcp"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
confirm_changeset = false
force_upload = false

# Development Environment (dev branch)  
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "pb-fm-mcp-dev"
s3_bucket = ""
s3_prefix = "pb-fm-mcp-dev"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
confirm_changeset = false
force_upload = false

# Default points to prod for backward compatibility  
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pb-fm-mcp-v2"
s3_bucket = ""
s3_prefix = "pb-fm-mcp"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
confirm_changeset = false
force_upload = false