AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: pb-fm-mcp - Provenance Blockchain + Figure Markets MCP Server

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12
  Api:
    Cors:
      AllowMethods: "'POST,GET,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,Accept'"
      AllowOrigin: "'*'"
      MaxAge: "'3600'"

Resources:
  PbFmMcpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: run.sh
      Description: "Unified MCP + REST Server with AWS Lambda Web Adapter"
      Layers:
        - arn:aws:lambda:us-west-1:753240598075:layer:LambdaAdapterLayerX86:25
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          PORT: 8000
      Events:
        McpApi:
          Type: Api
          Properties:
            Path: /mcp
            Method: ANY
        RestApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        RestApiDocs:
          Type: Api
          Properties:
            Path: /docs
            Method: ANY
        RestApiOpenApi:
          Type: Api
          Properties:
            Path: /openapi.json
            Method: ANY
        RestApiRoutes:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: python3.12

  # Note: EventBridge-based documentation updates removed due to permission requirements
  # Alternative solution: Use scripts/deploy_with_docs_update.sh for automated deployment with docs validation

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: !Sub "${AWS::StackName}-api-url"

  OpenApiUrl:
    Description: "OpenAPI specification URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/openapi.json"
    Export:
      Name: !Sub "${AWS::StackName}-openapi-url"

  SwaggerDocsUrl:
    Description: "Swagger UI documentation URL"
    Value: !Sub "https://generator3.swagger.io/index.html?url=https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/openapi.json"
    Export:
      Name: !Sub "${AWS::StackName}-swagger-docs-url"

  ValidationScript:
    Description: "Documentation validation script path"  
    Value: "./scripts/validate-and-update-docs.sh"
    Export:
      Name: !Sub "${AWS::StackName}-validation-script"

  DeploymentScript:
    Description: "Enhanced deployment script with documentation validation"
    Value: "./scripts/deploy_with_docs_update.sh" 
    Export:
      Name: !Sub "${AWS::StackName}-deployment-script"

